name: modeling-101
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip

  # science packages
  - numpy
  - pandas
  - scipy
  - statsmodels

  # modeling
  - pypsa

  # visualization
  - plotly
  - matplotlib
  - seaborn
  - bokeh
  
  
  
  
